-- 1. Board (칸반/리스트 보드)
create table board
(
    id         integer generated by default as identity primary key,
    name       varchar(100) not null,
    summary    varchar(80),
    project_id integer,
    sort_order integer default 0,
    is_active  integer default 1 not null, -- 0: 비활성, 1: 활성
    type       varchar(30),
    created_at timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_board_active check (is_active in (0, 1)),
    constraint check_board_sort check (sort_order >= 0)
);
create index idx_board_project_id on board (project_id);

-- 2. Board Member
create table board_member
(
    id         bigint generated by default as identity primary key,
    board_id   integer,
    member_id  integer,
    role_name  varchar(20) default 'MEMBER' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint uq_board_member unique (board_id, member_id)
);
create index idx_board_member_board_id on board_member (board_id);
create index idx_board_member_member_id on board_member (member_id);

-- 3. Channel (채널)
create table channel
(
    id         integer generated by default as identity primary key,
    name       varchar(100),
    project_id integer,
    workspace_id integer,
    issue_id   bigint,
    dm_pair_key varchar(120),
    agent_key  varchar(100),
    type       varchar(30) default 'GENERAL' not null,
    scope      varchar(20) default 'PROJECT' not null,
    status     varchar(20) default 'ACTIVE' not null,
    sort_order integer default 0 not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_channel_status check (status in ('ACTIVE', 'ARCHIVED')),
    constraint check_channel_type check (type in ('GENERAL', 'ISSUE', 'DM', 'AGENT', 'NOTICE')),
    constraint check_channel_scope check (scope in ('PROJECT', 'WORKSPACE'))
);
create unique index uq_channel_issue_id on channel (issue_id);
create unique index uq_channel_project_dm_pair_key on channel (project_id, dm_pair_key);
create unique index uq_channel_project_notice on channel (project_id) where type = 'NOTICE' and scope = 'PROJECT';
create unique index uq_channel_workspace_notice on channel (workspace_id) where type = 'NOTICE' and scope = 'WORKSPACE';
create index idx_channel_type on channel (type);
create index idx_channel_scope on channel (scope);
create index idx_channel_workspace_id on channel (workspace_id);
create index idx_channel_agent_key on channel (agent_key);

-- 4. Channel Member
create table channel_member
(
    id          bigint generated by default as identity primary key,
    channel_id integer,
    member_id   integer,
    role_name   varchar(20) default 'MEMBER' not null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_channel_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    constraint uq_channel_member unique (channel_id, member_id)
);
create index idx_channel_member_channel_id on channel_member (channel_id);
create index idx_channel_member_member_id on channel_member (member_id);

-- 5. Feedback (채팅 리액션용 피드백 아이콘)
create table feedback
(
    id            integer generated by default as identity primary key,
    name          varchar(50) not null,
    icon_img_path varchar(512),
    created_at    timestamp with time zone default CURRENT_TIMESTAMP
);

-- 6. Issue (이슈/할 일)
create table issue
(
    id         bigint generated by default as identity primary key,
    title      varchar(255) not null,
    content    text,
    board_id   integer,
    status     varchar(50) default 'BACKLOG' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_issue_status check (status in ('BACKLOG', 'IN_PROGRESS', 'IN_REVIEW', 'DONE'))
);
create index idx_issue_board_id on issue (board_id);

-- 7. Issue Member
create table issue_member
(
    id         bigint generated by default as identity primary key,
    issue_id   bigint,
    member_id  integer,
    role_name  varchar(50) not null, -- REPORTER, ASSIGNEE 등
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_issue_role check (role_name in ('REPORTER', 'ASSIGNEE', 'REVIEWER', 'WATCHER')),
    constraint uq_issue_member unique (issue_id, member_id)
);
create index idx_issue_member_issue_id on issue_member (issue_id);
create index idx_issue_member_member_id on issue_member (member_id);

-- 8. License (라이선스 상품 정의)
create table license
(
    id           bigint generated by default as identity primary key,
    type         varchar(20) not null,
    price        numeric(10, 2) not null,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_license_price check (price >= 0),
    constraint check_license_type check (type in (
        'WORKSPACE_LIFETIME',
        'WORKSPACE_MONTHLY',
        'WORKSPACE_YEARLY',
        'PROJECT_LIFETIME',
        'PROJECT_MONTHLY',
        'PROJECT_YEARLY'
    ))
);

-- 9. Member (사용자 계정)
create table member
(
    id         integer generated by default as identity primary key,
    name       varchar(50)  not null,
    password   varchar(255) not null,
    email      varchar(255) not null
        constraint member_email_unique
            unique,
    img_url    varchar(512),
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 10. Member License (사용자 라이선스)
create table member_license
(
    id           bigint generated by default as identity primary key,
    member_id    integer not null,
    license_id   bigint not null,
    status       varchar(20) default 'AVAILABLE' not null,
    price        numeric(10, 2) not null,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,
    expired_at   timestamp with time zone not null,
    workspace_id integer, -- 할당된 workspace_id 기록
    project_id   integer, -- 할당된 project_id 기록

    constraint check_member_license_status check (status in ('AVAILABLE', 'USED', 'EXPIRED')),
    constraint check_member_license_price check (price >= 0)
);
create index idx_member_license_member on member_license (member_id);
create index idx_member_license_license_id on member_license (license_id);
create index idx_member_license_status on member_license (status);
create index idx_member_license_workspace_id on member_license (workspace_id);
create index idx_member_license_project_id on member_license (project_id);

-- 11. Message (메시지)
create table message
(
    id          bigint generated by default as identity primary key,
    channel_id integer,
    content     text not null,
    created_by  integer,
    type       varchar(20) default 'USER' not null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_message_type check (type in ('SYSTEM', 'USER', 'AGENT'))
);
create index idx_message_type on message (type);
create index idx_message_channel_id on message (channel_id);

-- 12. Message Feedback
create table message_feedback
(
    id          bigint generated by default as identity primary key,
    message_id  bigint,
    feedback_id integer,
    created_by  integer,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP,
    constraint uq_message_feedback unique (message_id, feedback_id, created_by)
);
create index idx_message_feedback_message_id on message_feedback (message_id);
create index idx_message_feedback_feedback_id on message_feedback (feedback_id);
create index idx_message_feedback_created_by on message_feedback (created_by);

-- 13. Page (위키/문서)
create table page
(
    id         integer generated by default as identity primary key,
    title      varchar(255) not null,
    content    text,
    project_id integer,
    parent_id  integer,
    sort_order integer default 0,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 14. Page Member
create table page_member
(
    id         bigint generated by default as identity primary key,
    page_id    integer,
    member_id  integer,
    role_name  varchar(20) not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_page_role check (role_name in ('OWNER', 'EDITOR', 'VIEWER')),
    constraint uq_page_member unique (page_id, member_id)
);
create index idx_page_member_page_id on page_member (page_id);
create index idx_page_member_member_id on page_member (member_id);

-- 15. Payment (결제 이력 - www.baeun.com 스토어 기록용)
create table payment
(
    id               bigint generated by default as identity primary key,
    member_id        integer not null,
    license_id       bigint,
    amount           numeric(10, 2) not null,
    payment_method   varchar(50) not null,
    transaction_ref  varchar(255),
    created_at       timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_payment_amount check (amount > 0)
);
create index idx_payment_license_id on payment (license_id);

-- 16. Project (프로젝트)
create table project
(
    id           integer generated by default as identity primary key,
    name         varchar(100) not null,
    workspace_id integer,
    sort_order   integer default 0,
    img_url      varchar(512),
    theme_json   jsonb,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,
    is_default   boolean default false, -- 최초 1개 무료 프로젝트 여부
    license_id   bigint, -- 유료 라이선스 연결

    constraint check_project_sort check (sort_order >= 0)
);
create index idx_project_workspace_id on project (workspace_id);

-- 17. Project Member
create table project_member
(
    id         bigint generated by default as identity primary key,
    project_id integer,
    member_id  integer,
    role_name  varchar(20) default 'MEMBER' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_project_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    constraint uq_project_member unique (project_id, member_id)
);
create index idx_project_member_project_id on project_member (project_id);
create index idx_project_member_member_id on project_member (member_id);

-- 18. Session (PostgreSQL 세션 스토어)
create table session
(
    sid    varchar      not null primary key,
    sess   json         not null,
    expire timestamp(6) not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
create index idx_session_expire on session (expire);
create index idx_session_user_id on session ((sess ->> 'userId'));

-- 19. Workspace (워크스페이스)
create table workspace
(
    id         integer generated by default as identity primary key,
    name       varchar(100) not null,
    member_id  integer,
    sort_order integer default 0,
    img_url    varchar(512),
    theme_json jsonb,
    is_default boolean default false, -- 회원가입 시 무료 제공 여부
    license_id bigint, -- 유료 라이선스 연결

    constraint check_workspace_sort check (sort_order >= 0)
);
create index idx_workspace_member_id on workspace (member_id);

-- 20. Workspace Member (워크스페이스 참여 멤버 및 권한)
create table workspace_member
(
    id           bigint generated by default as identity primary key,
    workspace_id integer,
    member_id    integer,
    role_name    varchar(20) default 'MEMBER' not null,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_workspace_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    constraint uq_workspace_member unique (workspace_id, member_id)
);
create index idx_ws_member_ws_id on workspace_member (workspace_id);
create index idx_ws_member_mem_id on workspace_member (member_id);

alter table board
    add constraint board_project_id_fkey
        foreign key (project_id) references project(id) on delete cascade;

alter table board_member
    add constraint board_member_board_id_fkey
        foreign key (board_id) references board(id) on delete cascade;

alter table board_member
    add constraint board_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table channel
    add constraint channel_project_id_fkey
        foreign key (project_id) references project(id) on delete cascade;

alter table channel
    add constraint channel_workspace_id_fkey
        foreign key (workspace_id) references workspace(id) on delete cascade;

alter table channel
    add constraint channel_issue_id_fkey
        foreign key (issue_id) references issue(id) on delete cascade;

alter table channel_member
    add constraint channel_member_channel_id_fkey
        foreign key (channel_id) references channel(id) on delete cascade;

alter table channel_member
    add constraint channel_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table issue
    add constraint issue_board_id_fkey
        foreign key (board_id) references board(id) on delete cascade;

alter table issue_member
    add constraint issue_member_issue_id_fkey
        foreign key (issue_id) references issue(id) on delete cascade;

alter table issue_member
    add constraint issue_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table member_license
    add constraint member_license_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table member_license
    add constraint member_license_license_id_fkey
        foreign key (license_id) references license(id);

alter table member_license
    add constraint member_license_workspace_id_fkey
        foreign key (workspace_id) references workspace(id);

alter table member_license
    add constraint member_license_project_id_fkey
        foreign key (project_id) references project(id);

alter table message
    add constraint message_channel_id_fkey
        foreign key (channel_id) references channel(id) on delete cascade;

alter table message
    add constraint message_created_by_fkey
        foreign key (created_by) references member(id) on delete set null;

alter table message_feedback
    add constraint message_feedback_message_id_fkey
        foreign key (message_id) references message(id) on delete cascade;

alter table message_feedback
    add constraint message_feedback_feedback_id_fkey
        foreign key (feedback_id) references feedback(id) on delete cascade;

alter table message_feedback
    add constraint message_feedback_created_by_fkey
        foreign key (created_by) references member(id) on delete cascade;

alter table page
    add constraint page_project_id_fkey
        foreign key (project_id) references project(id) on delete cascade;

alter table page
    add constraint page_parent_id_fkey
        foreign key (parent_id) references page(id) on delete cascade;

alter table page_member
    add constraint page_member_page_id_fkey
        foreign key (page_id) references page(id) on delete cascade;

alter table page_member
    add constraint page_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table payment
    add constraint payment_member_id_fkey
        foreign key (member_id) references member(id);

alter table payment
    add constraint payment_license_id_fkey
        foreign key (license_id) references member_license(id);

alter table project
    add constraint project_workspace_id_fkey
        foreign key (workspace_id) references workspace(id) on delete cascade;

alter table project
    add constraint project_license_id_fkey
        foreign key (license_id) references member_license(id);

alter table project_member
    add constraint project_member_project_id_fkey
        foreign key (project_id) references project(id) on delete cascade;

alter table project_member
    add constraint project_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;

alter table workspace
    add constraint workspace_member_id_fkey
        foreign key (member_id) references member(id) on delete set null;

alter table workspace
    add constraint workspace_license_id_fkey
        foreign key (license_id) references member_license(id);

alter table workspace_member
    add constraint workspace_member_workspace_id_fkey
        foreign key (workspace_id) references workspace(id) on delete cascade;

alter table workspace_member
    add constraint workspace_member_member_id_fkey
        foreign key (member_id) references member(id) on delete cascade;
