/* =========================================================
   FULL DDL - PostgreSQL
   - snake_case
   - PK: pk_<table>
   - FK: fk_<from>_<col>__<to>
   - UQ: uq_<table>_<cols>
   - CK: ck_<table>_<col>
   - IDX: ix_<table>_<cols>
   ========================================================= */

-- =========================
-- FEEDBACK
-- =========================
create table feedback (
    id         integer generated by default as identity,
    name       varchar(50) not null,
    icon_path  varchar(512),
    created_at timestamptz not null default current_timestamp,
    constraint pk_feedback primary key (id)
);

-- =========================
-- LICENSE (상품 마스터)
-- =========================
create table license (
    id         bigint generated by default as identity,
    type       varchar(30) not null,
    price      numeric(10,2) not null,
    created_at timestamptz not null default current_timestamp,

    constraint pk_license primary key (id),
    constraint ck_license_type check (
        type in (
            'WORKSPACE_LIFETIME',
            'WORKSPACE_MONTHLY',
            'WORKSPACE_YEARLY',
            'PROJECT_LIFETIME',
            'PROJECT_MONTHLY',
            'PROJECT_YEARLY'
        )
    ),
    constraint ck_license_price check (price >= 0)
);

-- =========================
-- MEMBER
-- =========================
create table member (
    id         integer generated by default as identity,
    name       varchar(50) not null,
    password   varchar(255) not null,
    email      varchar(255) not null,
    avatar_url varchar(512),
    created_at timestamptz not null default current_timestamp,

    constraint pk_member primary key (id),
    constraint uq_member_email unique (email)
);

-- =========================
-- MEMBER_LICENSE (회원 보유 라이선스 인스턴스)
-- * workspace_id / project_id FK는 이후 ALTER로 연결(순환 참조 방지)
-- =========================
create table member_license (
    id           bigint generated by default as identity,
    member_id    integer not null,
    license_id   bigint not null,
    status       varchar(20) not null default 'AVAILABLE',
    price        numeric(10,2) not null,
    created_at   timestamptz not null default current_timestamp,
    expires_at   timestamptz not null,
    workspace_id integer,
    project_id   integer,

    constraint pk_member_license primary key (id),
    constraint fk_member_license_member_id__member
        foreign key (member_id) references member(id) on delete cascade,
    constraint fk_member_license_license_id__license
        foreign key (license_id) references license(id),

    constraint ck_member_license_status check (status in ('AVAILABLE','USED','EXPIRED')),
    constraint ck_member_license_price check (price >= 0)
);

create index ix_member_license_member_id    on member_license(member_id);
create index ix_member_license_license_id   on member_license(license_id);
create index ix_member_license_status       on member_license(status);
create index ix_member_license_workspace_id on member_license(workspace_id);
create index ix_member_license_project_id   on member_license(project_id);

-- =========================
-- SESSION
-- =========================
create table session (
    sid        varchar not null,
    sess       json not null,
    expires_at timestamp(6) not null,
    created_at timestamptz not null default current_timestamp,

    constraint pk_session primary key (sid)
);

create index ix_session_expires_at on session(expires_at);
create index ix_session_user_id    on session ((sess ->> 'userId'));

-- =========================
-- WORKSPACE
-- (원본 member_id → owner_id 로 명확화)
-- (원본 license_id → member_license_id 로 명확화)
-- =========================
create table workspace (
    id                integer generated by default as identity,
    name              varchar(100) not null,
    owner_id          integer,
    sort_order        integer not null default 0,
    avatar_url        varchar(512),
    theme_json        jsonb,
    is_default        boolean not null default false,
    member_license_id bigint,

    constraint pk_workspace primary key (id),
    constraint fk_workspace_owner_id__member
        foreign key (owner_id) references member(id) on delete set null,
    constraint fk_workspace_member_license_id__member_license
        foreign key (member_license_id) references member_license(id),
    constraint ck_workspace_sort_order check (sort_order >= 0)
);

create index ix_workspace_owner_id on workspace(owner_id);

-- member_license.workspace_id FK 연결(순환 참조 해소)
alter table member_license
    add constraint fk_member_license_workspace_id__workspace
        foreign key (workspace_id) references workspace(id);

-- =========================
-- PROJECT
-- (원본 license_id → member_license_id 로 명확화)
-- =========================
create table project (
    id                integer generated by default as identity,
    name              varchar(100) not null,
    workspace_id      integer not null,
    sort_order        integer not null default 0,
    avatar_url        varchar(512),
    theme_json        jsonb,
    created_at        timestamptz not null default current_timestamp,
    is_default        boolean not null default false,
    member_license_id bigint,

    constraint pk_project primary key (id),
    constraint fk_project_workspace_id__workspace
        foreign key (workspace_id) references workspace(id) on delete cascade,
    constraint fk_project_member_license_id__member_license
        foreign key (member_license_id) references member_license(id),
    constraint ck_project_sort_order check (sort_order >= 0)
);

create index ix_project_workspace_id on project(workspace_id);

-- member_license.project_id FK 연결(순환 참조 해소)
alter table member_license
    add constraint fk_member_license_project_id__project
        foreign key (project_id) references project(id);

-- =========================
-- KANBAN
-- (원본 is_active int(0/1) → boolean)
-- =========================
create table kanban (
    id         integer generated by default as identity,
    name       varchar(60) not null,
    project_id integer not null,
    sort_order integer not null default 0,
    is_active  boolean not null default true,
    type       varchar(30),
    created_at timestamptz not null default current_timestamp,
    summary    varchar(80),

    constraint pk_kanban primary key (id),
    constraint fk_kanban_project_id__project
        foreign key (project_id) references project(id) on delete cascade,
    constraint ck_kanban_sort_order check (sort_order >= 0)
);

create index ix_kanban_project_id on kanban(project_id);

-- =========================
-- CHANNEL
-- * task_id FK는 이후 ALTER로 연결(순환 참조 방지: task.channel_id ↔ channel.task_id)
-- =========================
create table channel (
    id           integer generated by default as identity,
    name         varchar(100),
    project_id   integer,
    type         varchar(30) not null,
    sort_order   integer not null default 0,
    created_at   timestamptz not null default current_timestamp,

    status       varchar(20) not null default 'ACTIVE',
    dm_pair_key  varchar(120),
    agent_key    varchar(100),
    workspace_id integer not null,
    scope        varchar(20) not null default 'PROJECT',
    task_id      bigint,

    constraint pk_channel primary key (id),

    constraint fk_channel_project_id__project
        foreign key (project_id) references project(id) on delete cascade,
    constraint fk_channel_workspace_id__workspace
        foreign key (workspace_id) references workspace(id) on delete cascade,

    constraint uq_channel_dm_pair_key unique (dm_pair_key),

    constraint ck_channel_type check (type in ('GENERAL','NOTICE','DM','TASK','AGENT')),
    constraint ck_channel_status check (status in ('ACTIVE','ARCHIVED')),
    constraint ck_channel_scope check (scope in ('PROJECT','WORKSPACE')),
    constraint ck_channel_sort_order check (sort_order >= 0)
);

-- =========================
-- TASK
-- =========================
create table task (
    id         bigint generated by default as identity,
    title      varchar(255) not null,
    content    text,
    kanban_id  integer not null,
    status     varchar(50) not null default 'BACKLOG',
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,
    channel_id integer,

    constraint pk_task primary key (id),
    constraint fk_task_kanban_id__kanban
        foreign key (kanban_id) references kanban(id) on delete cascade,
    constraint fk_task_channel_id__channel
        foreign key (channel_id) references channel(id) on delete set null,
    constraint ck_task_status check (status in ('BACKLOG','PENDING','IN_PROGRESS','IN_REVIEW','DONE'))
);

create index ix_task_kanban_id on task(kanban_id);

alter table channel
    add constraint fk_channel_task_id__task
        foreign key (task_id) references task(id) on delete cascade;

-- =========================
-- KANBAN_MEMBER
-- =========================
create table kanban_member (
    id         bigint generated by default as identity,
    kanban_id  integer not null,
    member_id  integer not null,
    role_name  varchar(20) not null default 'MEMBER',
    created_at timestamptz not null default current_timestamp,

    constraint pk_kanban_member primary key (id),
    constraint fk_kanban_member_kanban_id__kanban
        foreign key (kanban_id) references kanban(id) on delete cascade,
    constraint fk_kanban_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,
    constraint uq_kanban_member_kanban_id_member_id unique (kanban_id, member_id)
);

create index ix_kanban_member_kanban_id on kanban_member(kanban_id);
create index ix_kanban_member_member_id on kanban_member(member_id);

-- =========================
-- CHANNEL_MEMBER
-- =========================
create table channel_member (
    id         bigint generated by default as identity,
    channel_id integer not null,
    member_id  integer not null,
    role_name  varchar(20) not null default 'MEMBER',
    created_at timestamptz not null default current_timestamp,

    constraint pk_channel_member primary key (id),
    constraint fk_channel_member_channel_id__channel
        foreign key (channel_id) references channel(id) on delete cascade,
    constraint fk_channel_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,

    constraint ck_channel_member_role_name check (role_name in ('OWNER','ADMIN','MEMBER')),
    constraint uq_channel_member_channel_id_member_id unique (channel_id, member_id)
);

create index ix_channel_member_channel_id on channel_member(channel_id);
create index ix_channel_member_member_id  on channel_member(member_id);

-- =========================
-- TASK_MEMBER
-- =========================
create table task_member (
    id         bigint generated by default as identity,
    task_id    bigint not null,
    member_id  integer not null,
    role_name  varchar(50) not null,
    created_at timestamptz not null default current_timestamp,

    constraint pk_task_member primary key (id),
    constraint fk_task_member_task_id__task
        foreign key (task_id) references task(id) on delete cascade,
    constraint fk_task_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,

    constraint ck_task_member_role_name check (role_name in ('REPORTER','ASSIGNEE','REVIEWER','WATCHER')),
    constraint uq_task_member_task_id_member_id unique (task_id, member_id)
);

create index ix_task_member_task_id on task_member(task_id);
create index ix_task_member_member_id on task_member(member_id);

-- =========================
-- MESSAGE
-- =========================
create table message (
    id         bigint generated by default as identity,
    channel_id integer not null,
    content    text not null,
    created_by integer,
    created_at timestamptz not null default current_timestamp,
    type       varchar(10) not null default 'USER',

    constraint pk_message primary key (id),
    constraint fk_message_channel_id__channel
        foreign key (channel_id) references channel(id) on delete cascade,
    constraint fk_message_created_by__member
        foreign key (created_by) references member(id) on delete set null,
    constraint ck_message_type check (type in ('USER','SYSTEM','AGENT'))
);

create index ix_message_channel_id on message(channel_id);

-- =========================
-- MESSAGE_FEEDBACK
-- =========================
create table message_feedback (
    id          bigint generated by default as identity,
    message_id  bigint not null,
    feedback_id integer not null,
    created_by  integer not null,
    created_at  timestamptz not null default current_timestamp,

    constraint pk_message_feedback primary key (id),

    constraint fk_message_feedback_message_id__message
        foreign key (message_id) references message(id) on delete cascade,
    constraint fk_message_feedback_feedback_id__feedback
        foreign key (feedback_id) references feedback(id) on delete cascade,
    constraint fk_message_feedback_created_by__member
        foreign key (created_by) references member(id) on delete cascade,

    constraint uq_message_feedback_message_id_feedback_id_created_by
        unique (message_id, feedback_id, created_by)
);

create index ix_message_feedback_message_id on message_feedback(message_id);
create index ix_message_feedback_feedback_id on message_feedback(feedback_id);
create index ix_message_feedback_created_by on message_feedback(created_by);

-- =========================
-- PAGE (위키/문서)
-- =========================
create table page (
    id         integer generated by default as identity,
    title      varchar(255) not null,
    content    text,
    project_id integer not null,
    parent_id  integer,
    sort_order integer not null default 0,
    created_at timestamptz not null default current_timestamp,
    updated_at timestamptz not null default current_timestamp,

    constraint pk_page primary key (id),

    constraint fk_page_project_id__project
        foreign key (project_id) references project(id) on delete cascade,
    constraint fk_page_parent_id__page
        foreign key (parent_id) references page(id) on delete cascade,

    constraint ck_page_sort_order check (sort_order >= 0)
);

-- =========================
-- PAGE_MEMBER (문서 권한)
-- =========================
create table page_member (
    id         bigint generated by default as identity,
    page_id    integer not null,
    member_id  integer not null,
    role_name  varchar(20) not null,
    created_at timestamptz not null default current_timestamp,

    constraint pk_page_member primary key (id),

    constraint fk_page_member_page_id__page
        foreign key (page_id) references page(id) on delete cascade,
    constraint fk_page_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,

    constraint ck_page_member_role_name check (role_name in ('OWNER','EDITOR','VIEWER')),
    constraint uq_page_member_page_id_member_id unique (page_id, member_id)
);

create index ix_page_member_page_id on page_member(page_id);
create index ix_page_member_member_id on page_member(member_id);

-- =========================
-- PROJECT_MEMBER
-- =========================
create table project_member (
    id         bigint generated by default as identity,
    project_id integer not null,
    member_id  integer not null,
    role_name  varchar(20) not null default 'MEMBER',
    created_at timestamptz not null default current_timestamp,

    constraint pk_project_member primary key (id),

    constraint fk_project_member_project_id__project
        foreign key (project_id) references project(id) on delete cascade,
    constraint fk_project_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,

    constraint ck_project_member_role_name check (role_name in ('OWNER','ADMIN','MEMBER')),
    constraint uq_project_member_project_id_member_id unique (project_id, member_id)
);

create index ix_project_member_project_id on project_member(project_id);
create index ix_project_member_member_id on project_member(member_id);

-- =========================
-- WORKSPACE_MEMBER
-- =========================
create table workspace_member (
    id           bigint generated by default as identity,
    workspace_id integer not null,
    member_id    integer not null,
    role_name    varchar(20) not null default 'MEMBER',
    created_at   timestamptz not null default current_timestamp,

    constraint pk_workspace_member primary key (id),

    constraint fk_workspace_member_workspace_id__workspace
        foreign key (workspace_id) references workspace(id) on delete cascade,
    constraint fk_workspace_member_member_id__member
        foreign key (member_id) references member(id) on delete cascade,

    constraint ck_workspace_member_role_name check (role_name in ('OWNER','ADMIN','MEMBER')),
    constraint uq_workspace_member_workspace_id_member_id unique (workspace_id, member_id)
);

create index ix_workspace_member_workspace_id on workspace_member(workspace_id);
create index ix_workspace_member_member_id on workspace_member(member_id);

-- =========================
-- NOTIFICATION
-- =========================
create table notification (
    id            bigint generated by default as identity,
    recipient_id  integer not null,
    actor_id      integer,
    type          varchar(60) not null,
    resource_type varchar(30),
    resource_id   bigint,
    project_id    integer,
    workspace_id  integer,
    title         varchar(255) not null,
    body          text,
    payload       jsonb not null default '{}'::jsonb,
    is_read       boolean not null default false,
    created_at    timestamptz not null default current_timestamp,
    read_at       timestamptz,

    constraint pk_notification primary key (id),

    constraint fk_notification_recipient_id__member
        foreign key (recipient_id) references member(id) on delete cascade,
    constraint fk_notification_actor_id__member
        foreign key (actor_id) references member(id) on delete set null
);

create index ix_notification_recipient_read_created
    on notification (recipient_id asc, is_read asc, created_at desc);
create index ix_notification_recipient_created
    on notification (recipient_id asc, created_at desc);
create index ix_notification_project_id
    on notification (project_id);
create index ix_notification_workspace_id
    on notification (workspace_id);

-- =========================
-- PAYMENT
-- (원본 payment.license_id(member_license 참조) → member_license_id로 명확화)
-- =========================
create table payment (
    id                bigint generated by default as identity,
    member_id         integer not null,
    member_license_id bigint,
    amount            numeric(10,2) not null,
    payment_method    varchar(50) not null,
    transaction_ref   varchar(255),
    created_at        timestamptz not null default current_timestamp,

    constraint pk_payment primary key (id),

    constraint fk_payment_member_id__member
        foreign key (member_id) references member(id),
    constraint fk_payment_member_license_id__member_license
        foreign key (member_license_id) references member_license(id),

    constraint ck_payment_amount check (amount > 0)
);

create index ix_payment_member_license_id on payment(member_license_id);