create table feedback (
    id integer generated by default as identity primary key,
    name varchar(50) not null,
    icon_img_path varchar(512),
    created_at timestamptz default CURRENT_TIMESTAMP
);
create table license (
    id bigint generated by default as identity primary key,
    -- 1. 리소스와 결제 주기를 분리
    target_resource varchar(30) not null check (
        target_resource in ('WORKSPACE', 'WORKSPACE_MEMBER', 'PROJECT')
    ),
    billing_cycle varchar(20) not null check (
        billing_cycle in ('LIFETIME', 'MONTHLY', 'YEARLY')
    ),
    -- (선택) 만약 '14일권', '3개월권' 등 유연한 기간이 필요해진다면
    -- duration_days integer, 또는 duration_months integer 를 추가할 수도 있습니다.
    -- 2. 가격 및 통화 정보
    price numeric(10, 2) not null check (price >= 0),
    currency varchar(3) default 'KRW' not null check (currency in ('KRW', 'USD')),
    -- 3. 다국어 키 및 판매 상태
    name varchar(120),
    name_i18n_key varchar(120),
    is_active boolean default true not null,
    -- 판매 중단된 요금제는 false로 업데이트
    created_at timestamptz default CURRENT_TIMESTAMP,
    updated_at timestamptz default CURRENT_TIMESTAMP,
    -- 필요에 따라 동일한 리소스+주기+통화의 조합이 중복되지 않게 관리할 수도 있습니다.
    constraint uq_license_resource_cycle unique (target_resource, billing_cycle, currency)
);
create table payment (
    id bigint generated by default as identity primary key,
    -- 결제를 수행한 주체 (회원 탈퇴 시 결제 내역은 유지하되 null 처리하거나, 비즈니스 룰에 따라 보존)
    member_id integer references member on delete
    set null,
        total_amount numeric(10, 2) not null check (total_amount >= 0),
        -- 결제 상태 관리
        status varchar(20) default 'SUCCESS' not null check (
            status in (
                'PENDING',
                'SUCCESS',
                'FAILED',
                'CANCELED',
                'REFUNDED'
            )
        ),
        -- PG사(포트원, 토스페이먼츠, 스트라이프 등)에서 발급하는 결제 고유 번호
        pg_transaction_id varchar(100),
        created_at timestamptz default CURRENT_TIMESTAMP,
        updated_at timestamptz default CURRENT_TIMESTAMP
);
create index idx_payment_member_id on payment (member_id);
create table purchased_license (
    id bigint generated by default as identity primary key,
    -- 어떤 결제를 통해 획득했는지 (결제 취소/환불 시 함께 처리하기 위함)
    payment_id bigint not null references payment on delete cascade,
    -- 어떤 요금제(라이선스)를 샀는지
    license_id bigint not null references license on delete restrict,
    -- [A] 퍼블릭 설정(/settings/plan)에서 '워크스페이스 슬롯'을 구매한 경우 소유자에게 귀속
    owner_member_id integer references member on delete cascade,
    -- [B] 워크스페이스 설정(/workspace/:id/settings/license)에서 '멤버/프로젝트 슬롯'을 구매한 경우 해당 워크스페이스에 귀속
    target_workspace_id integer references workspace on delete cascade,
    -- 구매한 슬롯의 개수 (개별로 1개씩 사면 1, 10개 묶음으로 사면 10)
    quantity integer default 1 not null check (quantity > 0),
    -- 이용권의 현재 상태 (결제가 환불되거나 기간이 끝나면 EXPIRED/CANCELED 등으로 변경)
    status varchar(20) default 'ACTIVE' not null check (
        status in ('ACTIVE', 'EXPIRED', 'CANCELED', 'REFUNDED')
    ),
    -- 이용 기간 (LIFETIME 요금제인 경우 end_date는 NULL)
    start_date timestamptz default CURRENT_TIMESTAMP not null,
    end_date timestamptz,
    created_at timestamptz default CURRENT_TIMESTAMP,
    updated_at timestamptz default CURRENT_TIMESTAMP,
    -- 무결성 체크: owner_member_id 와 target_workspace_id 둘 중 하나만 존재해야 함 (또는 비즈니스 로직에 따라 조절)
    constraint chk_license_target check (
        (
            owner_member_id is not null
            and target_workspace_id is null
        )
        or (
            owner_member_id is null
            and target_workspace_id is not null
        )
    )
);
create index idx_purchased_license_owner on purchased_license (owner_member_id)
where status = 'ACTIVE';
create index idx_purchased_license_workspace on purchased_license (target_workspace_id)
where status = 'ACTIVE';
create table member (
    id integer generated by default as identity primary key,
    name varchar(50) not null,
    password varchar(255) not null,
    email varchar(255) not null constraint member_email_unique unique,
    img_url varchar(512),
    created_at timestamptz default CURRENT_TIMESTAMP,
    role_name varchar(20) default 'MEMBER'
);
create table session (
    sid varchar not null primary key,
    sess json not null,
    expire timestamp(6) not null,
    created_at timestamptz default CURRENT_TIMESTAMP
);
create index idx_session_expire on session (expire);
create index idx_session_user_id on session ((sess->>'userId'));
create table workspace (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    member_id integer references member on delete
    set null,
        sort_order integer default 0 check (sort_order >= 0),
        img_url varchar(512),
        theme_json jsonb,
        is_default boolean default false,
        summary varchar(100)
);
create table project (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    workspace_id integer references workspace on delete cascade,
    sort_order integer default 0 check (sort_order >= 0),
    img_url varchar(512),
    theme_json jsonb,
    created_at timestamptz default CURRENT_TIMESTAMP,
    is_default boolean default false,
    summary varchar(100)
);
create table kanban (
    id integer generated by default as identity primary key,
    name varchar(60) not null,
    project_id integer references project on delete cascade,
    sort_order integer default 0 check (sort_order >= 0),
    type varchar(30),
    created_at timestamptz default CURRENT_TIMESTAMP,
    summary varchar(100),
    is_active boolean default true
);
create index idx_kanban_project_id on kanban (project_id);
create table kanban_member (
    id bigint generated by default as identity primary key,
    kanban_id integer constraint board_member_board_id_fkey references kanban on delete cascade,
    member_id integer constraint board_member_member_id_fkey references member on delete cascade,
    role_name varchar(20) default 'MEMBER',
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_kanban_member unique (kanban_id, member_id)
);
create index idx_kanban_member_kanban_id on kanban_member (kanban_id);
create index idx_kanban_member_member_id on kanban_member (member_id);
create table task (
    id bigint generated by default as identity constraint issue_pkey primary key,
    title varchar(255) not null,
    content text,
    kanban_id integer references kanban on delete cascade,
    status varchar(50) default 'BACKLOG' check (
        status in (
            'BACKLOG',
            'PENDING',
            'IN_PROGRESS',
            'IN_REVIEW',
            'DONE'
        )
    ),
    created_at timestamptz default CURRENT_TIMESTAMP,
    updated_at timestamptz default CURRENT_TIMESTAMP,
    priority smallint default 0
);
create table channel (
    id integer generated by default as identity primary key,
    name varchar(100),
    project_id integer references project on delete cascade,
    type varchar(30) check (
        type in ('GENERAL', 'NOTICE', 'DM', 'TASK', 'AGENT')
    ),
    sort_order integer default 0 not null,
    created_at timestamptz default CURRENT_TIMESTAMP,
    status varchar(20) default 'ACTIVE' check (status in ('ACTIVE', 'ARCHIVED')),
    dm_pair_key varchar(120) constraint uq_channel_dm_pair_key unique,
    agent_key varchar(100),
    workspace_id integer constraint channel_workspace_id_fk references workspace on delete cascade,
    scope varchar(20) default 'PROJECT' check (scope in ('PROJECT', 'WORKSPACE')),
    task_id bigint constraint channel_task_id_fk references task on delete cascade
);
create table channel_member (
    id bigint generated by default as identity primary key,
    channel_id integer references channel on delete cascade,
    member_id integer references member on delete cascade,
    role_name varchar(20) default 'MEMBER' check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_channel_member unique (channel_id, member_id)
);
create index idx_channel_member_channel_id on channel_member (channel_id);
create index idx_channel_member_member_id on channel_member (member_id);
create index idx_task_kanban_id on task (kanban_id);
create table task_member (
    id bigint generated by default as identity primary key,
    task_id bigint references task on delete cascade,
    member_id integer references member on delete cascade,
    role_name varchar(50) not null check (
        role_name in ('REPORTER', 'ASSIGNEE', 'REVIEWER', 'WATCHER')
    ),
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_task_member unique (task_id, member_id)
);
create index idx_task_member_task_id on task_member (task_id);
create index idx_task_member_member_id on task_member (member_id);
create table message (
    id bigint generated by default as identity primary key,
    channel_id integer references channel on delete cascade,
    content text not null,
    created_by integer references member on delete
    set null,
        created_at timestamptz default CURRENT_TIMESTAMP,
        type varchar(10) default 'USER' check (type in ('USER', 'SYSTEM', 'AGENT'))
);
create index idx_message_channel_id on message (channel_id);
create table message_feedback (
    id bigint generated by default as identity primary key,
    message_id bigint references message on delete cascade,
    feedback_id integer references feedback on delete cascade,
    created_by integer references member on delete cascade,
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_message_feedback unique (message_id, feedback_id, created_by)
);
create index idx_message_feedback_message_id on message_feedback (message_id);
create index idx_message_feedback_feedback_id on message_feedback (feedback_id);
create index idx_message_feedback_created_by on message_feedback (created_by);
create table page (
    id integer generated by default as identity primary key,
    title varchar(255) not null,
    content text,
    project_id integer references project on delete cascade,
    parent_id integer references page on delete cascade,
    sort_order integer default 0,
    created_at timestamptz default CURRENT_TIMESTAMP,
    updated_at timestamptz default CURRENT_TIMESTAMP
);
create table page_member (
    id bigint generated by default as identity primary key,
    page_id integer references page on delete cascade,
    member_id integer references member on delete cascade,
    role_name varchar(20) not null check (role_name in ('OWNER', 'EDITOR', 'VIEWER')),
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_page_member unique (page_id, member_id)
);
create index idx_page_member_page_id on page_member (page_id);
create index idx_page_member_member_id on page_member (member_id);
create index idx_project_workspace_id on project (workspace_id);
create table project_member (
    id bigint generated by default as identity primary key,
    project_id integer references project on delete cascade,
    member_id integer references member on delete cascade,
    role_name varchar(20) default 'MEMBER' check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_project_member unique (project_id, member_id)
);
create index idx_project_member_project_id on project_member (project_id);
create index idx_project_member_member_id on project_member (member_id);
create index idx_workspace_member_id on workspace (member_id);
create table workspace_member (
    id bigint generated by default as identity primary key,
    workspace_id integer references workspace on delete cascade,
    member_id integer references member on delete cascade,
    role_name varchar(20) default 'MEMBER' check (role_name in ('OWNER', 'ADMIN', 'MEMBER')),
    created_at timestamptz default CURRENT_TIMESTAMP,
    constraint uq_workspace_member unique (workspace_id, member_id)
);
create index idx_ws_member_ws_id on workspace_member (workspace_id);
create index idx_ws_member_mem_id on workspace_member (member_id);
create table notification (
    id bigint generated by default as identity primary key,
    recipient_id integer not null references member on delete cascade,
    actor_id integer references member on delete
    set null,
        type varchar(60) not null,
        resource_type varchar(30),
        resource_id bigint,
        project_id integer,
        workspace_id integer,
        title varchar(255) not null,
        body text,
        payload jsonb default '{}',
        is_read boolean default false not null,
        created_at timestamptz default CURRENT_TIMESTAMP not null,
        read_at timestamptz
);
create index idx_notification_recipient_read_created on notification (recipient_id asc, is_read asc, created_at desc);
create index idx_notification_recipient_created on notification (recipient_id asc, created_at desc);
create index idx_notification_project on notification (project_id);
create index idx_notification_workspace on notification (workspace_id);
create table message_attachment (
    id bigint generated by default as identity primary key,
    message_id bigint not null references message on delete cascade,
    object_path text not null,
    original_file_name text not null,
    mime_type varchar(255) not null,
    file_size_bytes bigint not null check (file_size_bytes >= 0),
    sort_order integer not null default 0,
    created_at timestamptz not null default current_timestamp
);
create index idx_message_attachment_message_id on message_attachment (message_id);