-- 1. Member (사용자 계정)
create table member
(
    id         integer generated by default as identity primary key,
    name       varchar(50)  not null,
    password   varchar(255) not null,
    email      varchar(255) not null
        constraint member_email_unique
            unique,
    img_url    varchar(512),
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 2. License (사용권 관리 - 워크스페이스 $10, 프로젝트 $3)
create table license
(
    id           bigint generated by default as identity primary key,
    member_id    integer not null references member(id) on delete cascade,
    type         varchar(20) not null,
    status       varchar(20) default 'AVAILABLE' not null,
    price        numeric(10, 2) not null,
    bought_at    timestamp with time zone default CURRENT_TIMESTAMP,
    expired_at   timestamp with time zone not null,
    target_id    integer, -- 할당된 workspace_id 또는 project_id 기록

    constraint check_license_type check (type in ('WORKSPACE', 'PROJECT')),
    constraint check_license_status check (status in ('AVAILABLE', 'USED', 'EXPIRED')),
    constraint check_license_price check (price >= 0)
);
create index idx_license_member on license (member_id);
create index idx_license_status on license (status);

-- 3. Payment (결제 이력 - www.baeun.com 스토어 기록용)
create table payment
(
    id               bigint generated by default as identity primary key,
    member_id        integer not null references member(id),
    license_id       bigint references license(id),
    amount           numeric(10, 2) not null,
    payment_method   varchar(50) not null,
    transaction_ref  varchar(255),
    created_at       timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_payment_amount check (amount > 0)
);

-- 4. Feedback (채팅 리액션용 피드백 아이콘)
create table feedback
(
    id            integer generated by default as identity primary key,
    name          varchar(50) not null,
    icon_img_path varchar(512)
);

-- 5. Workspace (워크스페이스)
create table workspace
(
    id         integer generated by default as identity primary key,
    name       varchar(100) not null,
    member_id  integer references member on delete set null,
    sort_order integer default 0,
    img_url    varchar(512),
    theme_json jsonb,
    is_default boolean default false, -- 회원가입 시 무료 제공 여부
    license_id bigint references license(id), -- 유료 라이선스 연결

    constraint check_workspace_sort check (sort_order >= 0)
);
create index idx_workspace_member_id on workspace (member_id);

-- 6. Workspace Member (워크스페이스 참여 멤버 및 권한)
create table workspace_member
(
    id           bigint generated by default as identity primary key,
    workspace_id integer references workspace on delete cascade,
    member_id    integer references member on delete cascade,
    role_name    varchar(20) default 'MEMBER' not null,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_workspace_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER'))
);
create index idx_ws_member_ws_id on workspace_member (workspace_id);
create index idx_ws_member_mem_id on workspace_member (member_id);

-- 7. Project (프로젝트)
create table project
(
    id           integer generated by default as identity primary key,
    name         varchar(100) not null,
    workspace_id integer references workspace on delete cascade,
    sort_order   integer default 0,
    img_url      varchar(512),
    theme_json   jsonb,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,
    is_default   boolean default false, -- 최초 1개 무료 프로젝트 여부
    license_id   bigint references license(id), -- 유료 라이선스 연결

    constraint check_project_sort check (sort_order >= 0)
);
create index idx_project_workspace_id on project (workspace_id);

-- 8. Project Member
create table project_member
(
    id         bigint generated by default as identity primary key,
    project_id integer references project on delete cascade,
    member_id  integer references member on delete cascade,
    role_name  varchar(20) default 'MEMBER' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_project_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER'))
);

-- 9. Board (칸반/리스트 보드)
create table board
(
    id         integer generated by default as identity primary key,
    name       varchar(100) not null,
    project_id integer references project on delete cascade,
    sort_order integer default 0,
    is_active  integer default 1 not null, -- 0: 비활성, 1: 활성
    type       varchar(30),
    created_at timestamp with time zone default CURRENT_TIMESTAMP,

    constraint check_board_active check (is_active in (0, 1)),
    constraint check_board_sort check (sort_order >= 0)
);
create index idx_board_project_id on board (project_id);

-- 10. Board Member
create table board_member
(
    id         bigint generated by default as identity primary key,
    board_id   integer references board on delete cascade,
    member_id  integer references member on delete cascade,
    role_name  varchar(20) default 'MEMBER' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 11. Issue (이슈/할 일)
create table issue
(
    id         bigint generated by default as identity primary key,
    title      varchar(255) not null,
    content    text,
    board_id   integer references board on delete cascade,
    status     varchar(50) default '백로그' not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    updated_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_issue_status check (status in ('백로그', '진행중', '검토중', '완료'))
);
create index idx_issue_board_id on issue (board_id);

-- 12. Issue Member
create table issue_member
(
    id         bigint generated by default as identity primary key,
    issue_id   bigint references issue on delete cascade,
    member_id  integer references member on delete cascade,
    role_name  varchar(50) not null, -- REPORTER, ASSIGNEE 등
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_issue_role check (role_name in ('REPORTER', 'ASSIGNEE', 'REVIEWER', 'WATCHER'))
);

-- 13. Page (위키/문서)
create table page
(
    id         integer generated by default as identity primary key,
    title      varchar(255) not null,
    content    text,
    project_id integer references project on delete cascade,
    parent_id  integer references page on delete cascade,
    sort_order integer default 0,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 14. Page Member
create table page_member
(
    id         bigint generated by default as identity primary key,
    page_id    integer references page on delete cascade,
    member_id  integer references member on delete cascade,
    role_name  varchar(20) not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_page_role check (role_name in ('OWNER', 'EDITOR', 'VIEWER'))
);

-- 15. Chatroom (채팅방)
create table chatroom
(
    id         integer generated by default as identity primary key,
    name       varchar(100),
    project_id integer references project on delete cascade,
    type       varchar(30),
    sort_order integer default 0 not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);

-- 16. Chatroom Member
create table chatroom_member
(
    id          bigint generated by default as identity primary key,
    chatroom_id integer references chatroom on delete cascade,
    member_id   integer references member on delete cascade,
    role_name   varchar(20) default 'MEMBER' not null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP,
    constraint check_chatroom_role check (role_name in ('OWNER', 'ADMIN', 'MEMBER'))
);

-- 17. Chat (메시지)
create table chat
(
    id          bigint generated by default as identity primary key,
    chatroom_id integer references chatroom on delete cascade,
    content     text not null,
    created_by  integer references member on delete set null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP
);
create index idx_chat_chatroom_id on chat (chatroom_id);

-- 18. Chat Feedback
create table chat_feedback
(
    id          bigint generated by default as identity primary key,
    chat_id     bigint references chat on delete cascade,
    feedback_id integer references feedback on delete cascade,
    created_by  integer references member on delete cascade,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP
);

-- 19. Session (PostgreSQL 세션 스토어)
create table session
(
    sid    varchar      not null primary key,
    sess   json         not null,
    expire timestamp(6) not null
);
create index idx_session_expire on session (expire);