-- 1. Member
create table member
(
    id         integer generated by default as identity primary key,
    name       varchar(50)  not null,
    password   varchar(255) not null,
    email      varchar(255) not null
        constraint member_email_unique
            unique,
    img_url    varchar(512),
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table member owner to prisma_migration;

-- 2. Feedback
create table feedback
(
    id            integer generated by default as identity primary key,
    name          varchar(50) not null,
    icon_img_path varchar(512)
);
alter table feedback owner to prisma_migration;

-- 3. Workspace
create table workspace
(
    id         integer generated by default as identity primary key,
    name       varchar(100) not null,
    member_id  integer
                            references member
                                on delete set null,
    sort_order integer default 0,
    img_url    varchar(512),
    theme_json jsonb,
    is_default boolean default false
);
alter table workspace owner to prisma_migration;
create index idx_workspace_member_id on workspace (member_id);

-- 4. Workspace Member (N:M 연결 테이블은 데이터가 많아질 수 있어 bigint 추천)
create table workspace_member
(
    id           bigint generated by default as identity primary key,
    workspace_id integer
        references workspace
            on delete cascade,
    member_id    integer
        references member
            on delete cascade,
    role_name    varchar(20)              default 'MEMBER'::character varying not null,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP
);
alter table workspace_member owner to prisma_migration;
create index idx_ws_member_ws_id on workspace_member (workspace_id);
create index idx_ws_member_mem_id on workspace_member (member_id);

-- 5. Project
create table project
(
    id           integer generated by default as identity primary key,
    name         varchar(100) not null,
    workspace_id integer
        references workspace
            on delete cascade,
    sort_order   integer                  default 0,
    img_url      varchar(512),
    theme_json   jsonb,
    created_at   timestamp with time zone default CURRENT_TIMESTAMP,
    is_default   boolean                  default false
);
alter table project owner to prisma_migration;
create index idx_project_workspace_id on project (workspace_id);

-- 6. Project Member (bigint 추천)
create table project_member
(
    id         bigint generated by default as identity primary key,
    project_id integer
        references project
            on delete cascade,
    member_id  integer
        references member
            on delete cascade,
    role_name  varchar(20)              default 'MEMBER'::character varying not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table project_member owner to prisma_migration;
create index idx_pj_member_pj_id on project_member (project_id);

-- 7. Board
create table board
(
    id         integer generated by default as identity primary key,
    name       varchar(100)                       not null,
    project_id integer
        references project
            on delete cascade,
    sort_order integer                  default 0,
    is_active  integer                  default 1 not null,
    type       varchar(30),
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table board owner to prisma_migration;
create index idx_board_project_id on board (project_id);

-- 8. Board Member
create table board_member
(
    id         bigint generated by default as identity primary key,
    board_id   integer
        references board
            on delete cascade,
    member_id  integer
        references member
            on delete cascade,
    role_name  varchar(20)              default 'MEMBER'::character varying not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table board_member owner to prisma_migration;

-- 9. Issue (업무 시스템에서 가장 많이 쌓이는 데이터 중 하나이므로 bigint 권장)
create table issue
(
    id         bigint generated by default as identity primary key,
    title      varchar(255)                                              not null,
    content    text,
    board_id   integer
        references board
            on delete cascade,
    status     varchar(50)              default '백로그'::character varying not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table issue owner to prisma_migration;
create index idx_issue_board_id on issue (board_id);

-- 10. Issue Member (FK인 issue_id도 bigint여야 함)
create table issue_member
(
    id         bigint generated by default as identity primary key,
    issue_id   bigint
        references issue
            on delete cascade,
    member_id  integer
        references member
            on delete cascade,
    role_name  varchar(50) not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table issue_member owner to prisma_migration;
create index idx_issue_member_issue on issue_member (issue_id);

-- 11. Page
create table page
(
    id         integer generated by default as identity primary key,
    title      varchar(255) not null,
    content    text,
    project_id integer
        references project
            on delete cascade,
    parent_id  integer
        references page
            on delete cascade,
    sort_order integer                  default 0,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table page owner to prisma_migration;
create index idx_page_project_id on page (project_id);
create index idx_page_parent_id on page (parent_id);

-- 12. Page Member
create table page_member
(
    id         bigint generated by default as identity primary key,
    page_id    integer
        references page
            on delete cascade,
    member_id  integer
        references member
            on delete cascade,
    role_name  varchar(20) not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table page_member owner to prisma_migration;

-- 13. Chatroom
create table chatroom
(
    id         integer generated by default as identity primary key,
    name       varchar(100),
    project_id integer
        references project
            on delete cascade,
    type       varchar(30),
    sort_order integer                  default 0 not null,
    created_at timestamp with time zone default CURRENT_TIMESTAMP
);
alter table chatroom owner to prisma_migration;
create index idx_chatroom_project_id on chatroom (project_id);

-- 14. Chatroom Member
create table chatroom_member
(
    id          bigint generated by default as identity primary key,
    chatroom_id integer
        references chatroom
            on delete cascade,
    member_id   integer
        references member
            on delete cascade,
    role_name   varchar(20)              default 'MEMBER'::character varying not null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP
);
alter table chatroom_member owner to prisma_migration;

-- 15. Chat (가장 데이터가 많이 쌓이는 곳 - bigint 필수)
create table chat
(
    id          bigint generated by default as identity primary key,
    chatroom_id integer
        references chatroom
            on delete cascade,
    content     text not null,
    created_by  integer
                     references member
                         on delete set null,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP
);
alter table chat owner to prisma_migration;
create index idx_chat_chatroom_id on chat (chatroom_id);

-- 16. Chat Feedback (bigint 권장 및 FK 연결)
create table chat_feedback
(
    id          bigint generated by default as identity primary key,
    chat_id     bigint
        references chat
            on delete cascade,
    feedback_id integer
        references feedback
            on delete cascade,
    created_by  integer
        references member
            on delete cascade,
    created_at  timestamp with time zone default CURRENT_TIMESTAMP
);
alter table chat_feedback owner to prisma_migration;
create index idx_chat_feedback_chat on chat_feedback (chat_id);

-- 17. Session
create table session
(
    sid    varchar      not null
        primary key,
    sess   json         not null,
    expire timestamp(6) not null
);
alter table session owner to prisma_migration;
create index idx_session_expire on session (expire);