CREATE TABLE IF NOT EXISTS webauthn_credential (
  id bigint generated by default as identity primary key,
  member_id integer not null references member on delete cascade,
  credential_id varchar(1024) not null,
  public_key bytea not null,
  counter bigint not null default 0,
  device_type varchar(32),
  backed_up boolean not null default false,
  transports varchar(255),
  nickname varchar(80),
  created_at timestamptz not null default CURRENT_TIMESTAMP,
  last_used_at timestamptz,
  constraint uq_webauthn_credential_credential_id unique (credential_id)
);

CREATE INDEX IF NOT EXISTS ix_webauthn_credential_member_id
  ON webauthn_credential (member_id);
