BEGIN;

CREATE TABLE IF NOT EXISTS notification (
  id bigint generated by default as identity primary key,
  recipient_id integer not null,
  actor_id integer,
  type varchar(60) not null,
  resource_type varchar(30),
  resource_id bigint,
  project_id integer,
  workspace_id integer,
  title varchar(255) not null,
  body text,
  payload jsonb default '{}'::jsonb not null,
  is_read boolean default false not null,
  created_at timestamp with time zone default CURRENT_TIMESTAMP not null,
  read_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_notification_recipient_read_created
  ON notification (recipient_id, is_read, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_recipient_created
  ON notification (recipient_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_notification_project
  ON notification (project_id);

CREATE INDEX IF NOT EXISTS idx_notification_workspace
  ON notification (workspace_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'notification_recipient_id_fkey'
  ) THEN
    ALTER TABLE notification
      ADD CONSTRAINT notification_recipient_id_fkey
      FOREIGN KEY (recipient_id) REFERENCES member(id) ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'notification_actor_id_fkey'
  ) THEN
    ALTER TABLE notification
      ADD CONSTRAINT notification_actor_id_fkey
      FOREIGN KEY (actor_id) REFERENCES member(id) ON DELETE SET NULL;
  END IF;
END $$;

COMMIT;
