ALTER TABLE member
  ADD COLUMN IF NOT EXISTS account_status varchar(20) NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE member
  DROP CONSTRAINT IF EXISTS member_account_status_check;

ALTER TABLE member
  ADD CONSTRAINT member_account_status_check
  CHECK (account_status IN ('ACTIVE', 'SUSPENDED'));

CREATE INDEX IF NOT EXISTS idx_member_account_status
  ON member (account_status);

CREATE TABLE IF NOT EXISTS admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id integer references member on delete set null,
  action varchar(60) not null,
  target_type varchar(30) not null,
  target_id bigint,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_created_at
  ON admin_audit_log (created_at desc);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_target
  ON admin_audit_log (target_type, target_id);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor
  ON admin_audit_log (actor_id, created_at desc);

CREATE TABLE IF NOT EXISTS admin_broadcast (
  id bigint generated by default as identity primary key,
  actor_id integer references member on delete set null,
  title varchar(255) not null,
  body text,
  target_type varchar(20) not null,
  workspace_id integer references workspace on delete set null,
  recipient_count integer not null default 0,
  created_at timestamptz not null default CURRENT_TIMESTAMP,
  CONSTRAINT admin_broadcast_target_type_check
    CHECK (target_type IN ('ALL', 'WORKSPACE', 'MEMBERS'))
);

CREATE INDEX IF NOT EXISTS idx_admin_broadcast_created_at
  ON admin_broadcast (created_at desc);
